name: Build SunamoFilesIndex

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoFilesIndex
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoFilesIndex/SunamoFilesIndex.csproj

    - name: Build
      run: dotnet build SunamoFilesIndex/SunamoFilesIndex.csproj --configuration Release --no-restore

  test:
    name: Test SunamoFilesIndex.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoFilesIndex.Tests/SunamoFilesIndex.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoFilesIndex.Tests/SunamoFilesIndex.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoFilesIndex.Tests/SunamoFilesIndex.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
